### ISSUE TITLE
Maybe there are something missing

### ISSUE THREAD

**Issue by ViesLink** [dob9601/CollaboDev#22]
Additional need：
**pip3 install -r requirements.txt
pip3 install whitenoise-5.2.0**

=======
Is it possible to increase the authority management, for example, the tasks that have been claimed can only be viewed by the owner and the undertaker？

**Comment by ViesLink** [comment]
By the way，excellent user experience and appearance design.

**Comment by dob9601** [comment]
Hey there, sadly thats not a feature. CollaboDev by and large has been abandoned - it was the project I used to learn Django, meaning there are some "interesting" quirks in it that made it very hard to maintain as time went on. I may have another go at some point at cleaning the project up but until that today I'm sorry to say that I'm not adding new features.

PRs, however, are welcome. If there is a feature you want to implement, go for it! I'm more than happy to review it
